CREATE TABLE [dbo].[Objf]
(
	[Id] BIGINT NOT NULL CONSTRAINT pkFileId PRIMARY KEY,
	[FileUId] UNIQUEIDENTIFIER NOT NULL ROWGUIDCOL UNIQUE DEFAULT NEWID(),
	[Md5] BINARY(16) NOT NULL,
	--[Data] VARBINARY(max) FILESTREAM NOT NULL
)
