CREATE TABLE [dbo].[ObjL]
(
	[Id] INT NOT NULL CONSTRAINT pkObjLId PRIMARY KEY CLUSTERED IDENTITY (1, 1),
	[ParentObjKId] BIGINT NOT NULL CONSTRAINT fkParentObjLObjkId REFERENCES dbo.ObjK ([Id]) ON DELETE CASCADE,
	[ParentObjRId] BIGINT NULL CONSTRAINT fkParentObjLObjrId REFERENCES dbo.ObjR ([Id]) ON DELETE CASCADE,
	[LinkObjKId] BIGINT NULL CONSTRAINT fkLinkObjKId REFERENCES dbo.ObjK ([Id]) ON DELETE NO ACTION,
	[LinkObjRId] BIGINT NULL CONSTRAINT fkLinkObjRId REFERENCES dbo.ObjR ([Id]) ON DELETE NO ACTION,
	[IsRemoved] BIT NOT NULL DEFAULT 0,
	[OnDelete] CHAR(1) NOT NULL DEFAULT 0,
	[SyncToken] INTEGER NOT NULL
);
