<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	  <UseWpf>True</UseWpf>
	  <RootNamespace>TecWare.PPSn</RootNamespace>
    <AssemblyName>PPSnDesktopTest</AssemblyName>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <FileAlignment>512</FileAlignment>
    <WarningLevel>4</WarningLevel>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PPSnDesktopUI\PPSnDesktopUI.csproj">
      <Project>{c7d09a93-da78-4b81-8d3c-260442c61c5f}</Project>
      <Name>PPSnDesktopUI</Name>
    </ProjectReference>
    <ProjectReference Include="..\PPSnUI\PPSnUI.csproj">
      <Project>{136cad3e-3599-4d02-9fce-334f2cf66ecd}</Project>
      <Name>PPSnUI</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup />
</Project>